
-- +migrate Up
CREATE TABLE IF NOT EXISTS `movies` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `original_title` VARCHAR(255) NOT NULL,
  `original_language` VARCHAR(255) NOT NULL,
  `overview` VARCHAR(1000) DEFAULT NULL,
  `poster_path` VARCHAR(2048) DEFAULT NULL,
  `backdrop_path` VARCHAR(2048) DEFAULT NULL,
  `adult` BOOLEAN NOT NULL DEFAULT FALSE,
  `release_date` TIMESTAMP DEFAULT NULL,
  `budget` INT DEFAULT NULL,
  `revenue` INT DEFAULT NULL,

  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- +migrate Down
DROP TABLE IF EXISTS `movies`;
